# Site settings
title: Miguel Lima
email: miguelsl2000@gmail.com
url: https://github.com/Aeziren
description: "Luiz Miguel Silva Lima Website and Portfolio"
keywords: "Luiz Miguel Silva Lima, website, portfolio, jobs, work, trabalhos"
skills: "Backend Developer"
meta_author: Lima Luiz

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: None

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "17e7ef"
  primary-rgb: "12,222,239"
  secondary: "ffffff"
  secondary-dark: "181818"

# Footer settings
footer:
  copyright: Luiz Miguel Silva Lima
  location: Location
  social: Follow Me!
  credits: Documents

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: linkedin
    url: https://www.linkedin.com/in/miguelsilvalima/
  - title: github
    url: https://github.com/aeziren
  - title: steam
    url: https://steamcommunity.com/id/aeziren/
  - title: discord
    url: https://discordapp.com/users/229376961783267328

# Postal address (add as many lines as necessary)
address:
  - line: 2490 Ourém
  - line: Santarém, Portugal

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
